### ISSUE TITLE
Support for literals

### ISSUE THREAD

**Issue by gtfierro** [gtfierro/hod#16]
This is how we'll store information; not going to be using the "links" anymore

**Comment by aslakjohansen** [comment]
# Background

The following building definition:

```turtle
@prefix brick: <http://buildsys.org/ontologies/Brick#> .
@prefix bf:    <http://buildsys.org/ontologies/BrickFrame#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ns:    <http://google.com#> .

ns:build  rdf:type        brick:Building .
ns:floor  rdf:type        brick:Floor .
ns:room1  rdf:type        brick:Room .
ns:room2  rdf:type        brick:Room .

ns:floor  bf:isLocatedIn  ns:build .
ns:room1  bf:isLocatedIn  ns:floor .
ns:room2  bf:isLocatedIn  ns:floor .

ns:room1  rdfs:label      "Room 1" .
ns:room2  rdfs:label      "Room 2" .
```

# Case 1 - Literals in the Output

Query:

```sparql
SELECT DISTINCT ?label
WHERE {
    ?room  rdf:type    brick:Room .
    ?room  rdfs:label  ?label .
};
```

Result using python rdflib:

```json
[
    [
        "Room 2"
    ],
    [
        "Room 1"
    ]
]
```

Result using HodDB:

```json
{
    "Rows": [
        {
            "?label": {
                "Namespace": "",
                "Value": "\"Room 1\""
            }
        },
        {
            "?label": {
                "Namespace": "",
                "Value": "\"Room 2\""
            }
        }
    ],
    "Links": null,
    "Count": 0
}
```

**Note:** The values include escaped double quotes bracketing the correct value.

# Case 2 - Literals in the Input

Query:

```sparql
SELECT DISTINCT ?room
WHERE {
    ?room  rdf:type    brick:Room .
    ?room  rdfs:label  "Room 1" .
};
```

Result using python rdflib:

```json
[
    [
        "http://google.com#room1"
    ]
]
```

Result using HodDB: `Error parsing: syntax error. Current line 78:64. Recent token '"Room 1"'`

**Comment by gtfierro** [comment]
I made some initial fixes concluding in https://github.com/gtfierro/hod/commit/d13442f9ed5149e65f6293c063984627f3659e0b to address this. It passes the two scenarios you've detailed. Haven't gotten a chance to write unit tests around this yet to see if I forgot anything, but at least it doesn't seem to break any existing behavior

**Comment by gtfierro** [comment]
Added a couple tests for literals support in queries. Going to mark this closed for now until we run into any issues with the implementation
