### ISSUE TITLE
Add support for namespace prefixes containing digits

### ISSUE THREAD

**Issue by aslakjohansen** [gtfierro/hod#17]
Currently, it seems, that namespace prefixes containing digits are not supported.

The attached [minimal_case.zip](https://github.com/gtfierro/hod/files/919615/minimal_case.zip) contains a TTL file and matching query (the `a` variant) which gives a simple result, and a version of the same TTL file and query containing a single digit in a used namespace prefix (the `b` variant). This gives a syntax error instead of the same result:

`Error parsing: syntax error. Current line 29:33. Recent token 'ns2:Large_City'`

As a query (like the following) can generate results in the affected namespace if it doesn't reference the affected namespace I suspect the issue is limited to the parser generator of the query language. 

```sparql
SELECT ?city
WHERE {
    ?city owl:subClassOf brick:City .
};
```

**Comment by gtfierro** [comment]
Should be fixed in https://github.com/gtfierro/hod/commit/834b0d5a1fbb377ba72bf8e1bc93348f9f9e271e
